import { useState, useEffect } from 'react';
import { DollarSign, FileText, Download, Calendar, Loader2 } from 'lucide-react';
import { supabase } from '../../supabaseClient';
import toast from 'react-hot-toast';

export default function AgentPayslips() {
    const [payslips, setPayslips] = useState([]);
    const [isLoading, setIsLoading] = useState(true);

    useEffect(() => {
        fetchMyPayslips();
    }, []);

    const fetchMyPayslips = async () => {
        try {
            // 1. Get the Agent's secure session token
            const { data: { session }, error: sessionError } = await supabase.auth.getSession();
            if (sessionError) throw sessionError;
            if (!session) return;

            // 2. Fetch only THIS agent's payroll records
            const response = await fetch(`https://bpo-backend-vemc.onrender.com/api/payroll?user_id=${session.user.id}`, {
                headers: {
                    'Authorization': `Bearer ${session.access_token}`
                }
            });

            if (!response.ok) throw new Error('Failed to fetch payslips');

            const data = await response.json();
            setPayslips(data);
        } catch (error) {
            console.error("Fetch Error:", error);
            toast.error("Could not load your payslips.");
        } finally {
            setIsLoading(false);
        }
    };

    // --- HELPER FUNCTIONS ---

    // Safely parse "YYYY-MM-DD" to "Month Year" (e.g., February 2026)
    const formatMonth = (dateString) => {
        if (!dateString) return '';
        const [year, month] = dateString.split('-');
        const date = new Date(year, month - 1);
        return date.toLocaleDateString('en-US', { month: 'long', year: 'numeric' });
    };

    const formatMoney = (amount) => {
        return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(amount || 0);
    };

    return (
        <div className="max-w-5xl mx-auto space-y-6">

            {/* Header */}
            <div className="flex items-center space-x-3 mb-8">
                <div className="p-3 bg-emerald-100 text-emerald-600 rounded-xl">
                    <DollarSign className="h-6 w-6" />
                </div>
                <div>
                    <h1 className="text-2xl font-bold text-slate-800">My Payslips</h1>
                    <p className="text-sm text-slate-500 mt-1">Review your monthly earnings, bonuses, and tax deductions.</p>
                </div>
            </div>

            {/* Payslips Feed */}
            <div className="space-y-4">
                {isLoading ? (
                    <div className="flex justify-center items-center p-12 bg-white rounded-2xl border border-slate-200 shadow-sm">
                        <Loader2 className="h-8 w-8 animate-spin text-emerald-600" />
                    </div>
                ) : payslips.length === 0 ? (
                    <div className="bg-white p-12 rounded-2xl border border-slate-200 text-center shadow-sm">
                        <FileText className="h-16 w-16 text-slate-300 mx-auto mb-4" />
                        <h3 className="text-xl font-bold text-slate-800">No Payslips Available</h3>
                        <p className="text-slate-500 mt-2">Your payroll records will appear here once generated by HR.</p>
                    </div>
                ) : (
                    payslips.map((slip) => {
                        const grossPay = Number(slip.final_salary) + Number(slip.tax_deduction);

                        return (
                            <div key={slip.id} className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden hover:shadow-md transition-shadow">

                                {/* Payslip Header */}
                                <div className="px-6 py-4 bg-slate-50 border-b border-slate-200 flex justify-between items-center">
                                    <div className="flex items-center space-x-2 text-slate-700 font-bold">
                                        <Calendar className="h-5 w-5 text-slate-400" />
                                        <span>{formatMonth(slip.month_year)}</span>
                                    </div>
                                    <button className="flex items-center px-3 py-1.5 text-sm font-medium text-blue-600 bg-blue-50 hover:bg-blue-100 rounded-lg transition-colors">
                                        <Download className="h-4 w-4 mr-1.5" /> PDF
                                    </button>
                                </div>

                                {/* Payslip Details Grid */}
                                <div className="p-6">
                                    <div className="grid grid-cols-2 md:grid-cols-4 gap-6">

                                        <div>
                                            <p className="text-sm font-medium text-slate-500 mb-1">Hours Logged</p>
                                            <p className="text-lg font-bold text-slate-800">{slip.total_hours}h</p>
                                        </div>

                                        <div>
                                            <p className="text-sm font-medium text-slate-500 mb-1">Gross Pay & Bonus</p>
                                            <p className="text-lg font-bold text-slate-800">{formatMoney(grossPay)}</p>
                                            {Number(slip.night_shift_bonus) > 0 && (
                                                <p className="text-xs font-medium text-indigo-600 mt-1">
                                                    Includes {formatMoney(slip.night_shift_bonus)} night premium
                                                </p>
                                            )}
                                        </div>

                                        <div>
                                            <p className="text-sm font-medium text-slate-500 mb-1">Taxes Withheld</p>
                                            <p className="text-lg font-bold text-red-600">-{formatMoney(slip.tax_deduction)}</p>
                                        </div>

                                        <div className="md:text-right">
                                            <p className="text-sm font-medium text-slate-500 mb-1">Net Take-Home</p>
                                            <p className="text-2xl font-black text-emerald-600">{formatMoney(slip.final_salary)}</p>
                                        </div>

                                    </div>
                                </div>

                            </div>
                        );
                    })
                )}
            </div>

        </div>
    );
}